const $=s=>document.querySelector(s);const IMG="https://image.tmdb.org/t/p/";let cache={};let current=null;
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const poster=x=>x?.poster_path?IMG+"w500"+x.poster_path:"https://placehold.co/500x750/151617/aaa?text=No+Poster";
const backdrop=x=>x?.backdrop_path?IMG+"original"+x.backdrop_path:poster(x); const title=x=>x?.title||x?.name||"Untitled"; const year=x=>(x?.release_date||x?.first_air_date||"").slice(0,4);
const settingsKey="luma-settings";let heroPool=[];let heroIndex=-1;let heroTimer=null;let southHindiItems=[];
function prefs(){try{return {...{accent:"d6b77c",autoplay:true,continue:true,motion:"full",density:"comfortable"},...JSON.parse(localStorage.getItem(settingsKey)||"{}")}}catch{return{accent:"d6b77c",autoplay:true,continue:true,motion:"full",density:"comfortable"}}}
function savePrefs(p){localStorage.setItem(settingsKey,JSON.stringify(p));applyPrefs()}
function applyPrefs(){const p=prefs();document.documentElement.style.setProperty("--gold","#"+p.accent);document.body.dataset.motion=p.motion;document.body.dataset.density=p.density;document.body.classList.toggle("hide-continue",!p.continue);const a=$("#autoplay");if(a)a.checked=p.autoplay;document.querySelectorAll(".preset").forEach(b=>b.classList.toggle("active",b.dataset.accent===p.accent));document.querySelectorAll("[data-motion]").forEach(b=>b.classList.toggle("active",b.dataset.motion===p.motion));document.querySelectorAll("[data-density]").forEach(b=>b.classList.toggle("active",b.dataset.density===p.density));}
function card(x){const id=x.id,type=x.media_type||(x.first_air_date?"tv":"movie"),p=getProgress()[`${type}:${id}`];return `<article class="card" data-id="${id}" data-type="${type}"><img loading="lazy" src="${poster(x)}" alt="${esc(title(x))}"><div class="ci"><div class="ct">${esc(title(x))}</div><div class="cm">${year(x)} · ★ ${(x.vote_average||0).toFixed(1)}</div></div>${p?`<div class="bar"><i style="width:${Math.min(100,p.progress||0)}%"></i></div>`:""}</article>`}
function bindCards(){document.querySelectorAll(".card").forEach(c=>c.onclick=()=>details(c.dataset.type,c.dataset.id))} function getProgress(){try{return JSON.parse(localStorage.getItem("luma-progress")||"{}")}catch{return{}}}
function renderGrid(id,data){$(id).innerHTML=(data||[]).filter(x=>x.poster_path).map(card).join("")||`<p class="muted">Nothing here yet.</p>`;bindCards()}
async function api(path){const r=await fetch(path);const d=await r.json();if(d.error)throw Error(d.error);return d}
function setHero(hero){if(!hero)return;current=hero;sessionStorage.setItem("luma-last-hero",String(hero.id));$("#heroImg").style.backgroundImage=`url('${backdrop(hero)}')`;$("#heroTitle").textContent=title(hero);$("#heroOverview").textContent=hero.overview||"";$("#heroMeta").innerHTML=`<span>${year(hero)}</span><span>•</span><span>${hero.media_type==="tv"?"Series":"Movie"}</span><span>•</span><span>★ ${(hero.vote_average||0).toFixed(1)}</span>`;$("#heroWatch").onclick=()=>play(hero.media_type==="tv"?"tv":"movie",hero.id,hero.media_type==="tv"?1:undefined,hero.media_type==="tv"?1:undefined);$("#heroInfo").onclick=()=>details(hero.media_type,hero.id)}
function nextHero(){if(!heroPool.length)return;heroIndex=(heroIndex+1)%heroPool.length;setHero(heroPool[heroIndex])}
function startHeroRotation(){if(heroTimer)clearInterval(heroTimer);if(heroPool.length>1)heroTimer=setInterval(nextHero,12000)}
function renderSouth(filter="all"){const items=filter==="all"?southHindiItems:southHindiItems.filter(x=>x.south_language===filter);renderGrid("#southHindiGrid",items)}
async function loadSouthHindi(){try{const d=await api("/api/south-hindi-dubbed");southHindiItems=d.results||[];renderSouth()}catch(e){$("#southHindiGrid").innerHTML='<p class="muted">South Hindi Dubbed database is unavailable right now.</p>'}}

async function home(){try{const d=await api("/api/home");heroPool=(d.trending?.results||[]).filter(x=>x.media_type!=="person"&&x.backdrop_path);if(heroPool.length){const last=Number(sessionStorage.getItem("luma-last-hero"));const candidates=heroPool.map((x,i)=>({x,i})).filter(v=>v.x.id!==last);const pick=candidates[Math.floor(Math.random()*candidates.length)]||{x:heroPool[0],i:0};heroIndex=pick.i;setHero(pick.x);startHeroRotation()}renderGrid("#movieGrid",(d.movies?.results||[]).map(x=>({...x,media_type:"movie"})));renderGrid("#seriesGrid",(d.series?.results||[]).map(x=>({...x,media_type:"tv"})));renderGrid("#topGrid",(d.top?.results||[]).map(x=>({...x,media_type:"movie"})));loadSouthHindi();renderContinue()}catch(e){showSetup(e.message)}}
function showSetup(msg){document.querySelector("main").innerHTML=`<section class="section setup" style="padding-top:160px"><small>SETUP REQUIRED</small><h2 style="margin-top:10px">Connect TMDB to populate LUMA.</h2><p class="muted">${esc(msg)}</p></section>`}
async function details(type,id){try{const d=await api(`/api/${type}/${id}`);cache[`${type}:${id}`]=d;const genres=(d.genres||[]).map(g=>`<span>${esc(g.name)}</span>`).join("");const cast=(d.credits?.cast||[]).filter(x=>x.profile_path).slice(0,10);const rec=(d.recommendations?.results||[]).filter(x=>x.poster_path).slice(0,8);const runtime=type==="movie"?d.runtime:(d.episode_run_time?.[0]||0);$("#modalBody").innerHTML=`<div class="cinema-cover" style="background-image:url('${backdrop(d)}')"><div class="cover-shade"></div><div class="cinema-copy"><small>${type==="tv"?"SERIES":"MOVIE"}</small><h1>${esc(title(d))}</h1><div class="detail-meta"><span>${year(d)}</span><span>★ ${(d.vote_average||0).toFixed(1)}</span>${runtime?`<span>${runtime} min</span>`:""}<span>${type==="tv"?`${d.number_of_seasons||0} Seasons`:""}</span></div><div class="chips">${genres}</div><p>${esc(d.overview||"No overview available.")}</p><div class="detail-actions"><button class="primary" id="detailWatch">▶ Watch now</button><button class="secondary" id="detailClose">Close</button></div></div></div><div class="detail-content">${cast.length?`<section><div class="subhead"><small>THE CAST</small><h2>People behind the story</h2></div><div class="cast-row">${cast.map(c=>`<article class="cast-card"><img src="${IMG}w185${c.profile_path}" alt="${esc(c.name)}"><b>${esc(c.name)}</b><span>${esc(c.character||"")}</span></article>`).join("")}</div></section>`:""}${type==="tv"?`<section class="episodes-section"><div class="subhead"><small>EPISODES</small><h2>Choose where to continue</h2></div><label class="season-label">Season <select id="seasonSelect">${(d.seasons||[]).filter(s=>s.season_number>0).map(s=>`<option value="${s.season_number}">${esc(s.name)}</option>`).join("")}</select></label><div id="episodes" class="episode-grid"></div></section>`:""}${rec.length?`<section><div class="subhead"><small>RECOMMENDED</small><h2>More like this</h2></div><div class="grid rec-grid">${rec.map(card).join("")}</div></section>`:""}</div>`;$("#modal").classList.add("open");document.body.style.overflow="hidden";$("#detailWatch").onclick=()=>play(type,id,type==="tv"?1:undefined,type==="tv"?1:undefined);$("#detailClose").onclick=closeModal;bindCards();if(type==="tv"){const sel=$("#seasonSelect");await season(id,sel.value);sel.onchange=()=>season(id,sel.value)}}catch(e){console.error(e)}}
async function season(id,n){const d=await api(`/api/tv/${id}/season/${n}`);$("#episodes").innerHTML=(d.episodes||[]).map(ep=>`<article class="episode-card" data-ep="${ep.episode_number}"><img src="${poster(ep.still_path?{poster_path:ep.still_path}:null)}"><div><b>E${ep.episode_number} · ${esc(ep.name)}</b><span>${Math.round(ep.runtime||0)} min</span><small>${esc(ep.overview||"")}</small></div></article>`).join("");document.querySelectorAll(".episode-card").forEach(c=>c.onclick=()=>play("tv",id,Number(n),Number(c.dataset.ep)))}
function play(type,id,season,episode){const pset=prefs(),accent=pset.accent,auto=pset.autoplay?"true":"false";const p=getProgress()[`${type}:${id}${type==="tv"?`:${season}:${episode}`:""}`];let url=`https://www.vidcore.org/embed/${type}/${id}`+(type==="tv"?`/${season||1}/${episode||1}`:"");const params=new URLSearchParams({autoPlay:auto,theme:accent});if(p?.timestamp)params.set("startAt",Math.floor(p.timestamp));url+=`?${params.toString()}`;$("#iframe").src=url;$("#player").classList.add("open");document.body.style.overflow="hidden";closeModal()}
function closeModal(){$("#modal").classList.remove("open");if(!$("#player").classList.contains("open"))document.body.style.overflow=""}function closePlayer(){$("#iframe").src="about:blank";$("#player").classList.remove("open");document.body.style.overflow=""}
function renderContinue(){const p=getProgress(),items=[];for(const [key,v] of Object.entries(p)){if(v.progress>1&&v.progress<99){const [type,id]=key.split(":");const d=cache[`${type}:${id}`]||cache[key];if(d)items.push({...d,media_type:type})}}renderGrid("#continueGrid",items);$("#continueSection").style.display=items.length&&prefs().continue?"block":"none"}
async function search(q){if(!q){$("#searchResults").innerHTML="";return}try{const d=await api("/api/search?q="+encodeURIComponent(q));$("#searchResults").innerHTML=(d.results||[]).filter(x=>x.media_type!=="person"&&x.poster_path).slice(0,10).map(x=>`<div class="result" data-id="${x.id}" data-type="${x.media_type}"><img src="${poster(x)}"><div><b>${esc(title(x))}</b><small>${year(x)} · ${x.media_type} · ★ ${(x.vote_average||0).toFixed(1)}</small></div></div>`).join("")||`<p class="muted">No matches found.</p>`;document.querySelectorAll(".result").forEach(x=>x.onclick=()=>{closeSearch();details(x.dataset.type,x.dataset.id)})}catch(e){$("#searchResults").innerHTML=`<p class="muted">Search is unavailable right now.</p>`}}
function discover(){const type=$("#discover").dataset.type||"movie";api(`/api/discover/${type}?sort_by=${encodeURIComponent($("#sort").value)}&with_genres=${$("#genre").value}`).then(d=>renderGrid("#discoverGrid",(d.results||[]).map(x=>({...x,media_type:type})))).catch(()=>{})}
function openSearch(){$("#search").classList.add("open");document.body.style.overflow="hidden";setTimeout(()=>$("#searchInput").focus(),100)}function closeSearch(){$("#search").classList.remove("open");if(!$("#modal").classList.contains("open")&&!$("#player").classList.contains("open"))document.body.style.overflow=""}
function openSettings(){$("#settings").classList.add("open");document.body.style.overflow="hidden";applyPrefs()}function closeSettings(){$("#settings").classList.remove("open");if(!$("#modal").classList.contains("open")&&!$("#player").classList.contains("open"))document.body.style.overflow=""}
function openMenu(){$("#mobileMenu").classList.add("open");document.body.style.overflow="hidden"}function closeMenu(){$("#mobileMenu").classList.remove("open");if(!$("#search").classList.contains("open")&&!$("#settings").classList.contains("open"))document.body.style.overflow=""}
$("#searchBtn").onclick=openSearch;$("#closeSearch").onclick=closeSearch;$("#searchInput").oninput=e=>search(e.target.value);$("#closeModal").onclick=closeModal;$("#closePlayer").onclick=closePlayer;$("#clearHistory").onclick=()=>{localStorage.removeItem("luma-progress");renderContinue()};$("#clearHistorySettings").onclick=()=>{localStorage.removeItem("luma-progress");renderContinue();closeSettings()};$("#settingsBtn").onclick=openSettings;$("#closeSettings").onclick=closeSettings;$("#menuBtn").onclick=openMenu;$("#closeMenu").onclick=closeMenu;$("#mobileSearch").onclick=()=>{closeMenu();openSearch()};$("#mobileSettings").onclick=()=>{closeMenu();openSettings()};
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{$("#discover").classList.remove("hidden");$("#discover").dataset.type=b.dataset.page;location.hash="discover";discover();window.scrollTo({top:document.querySelector("#discover").offsetTop-90,behavior:"smooth"})});document.querySelectorAll("[data-mobile-page]").forEach(a=>a.onclick=()=>{closeMenu();if(a.dataset.mobilePage==="discover"){$("#discover").classList.remove("hidden");$("#discover").dataset.type="movie";discover()}else if(a.dataset.mobilePage!=="home"){const target=$("#"+a.dataset.mobilePage);if(target)target.scrollIntoView({behavior:"smooth"})}});
$("#sort").onchange=discover;$("#genre").onchange=discover;document.querySelectorAll(".south-filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".south-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSouth(b.dataset.southFilter)});
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{const p=prefs();p.accent=b.dataset.accent;savePrefs(p)});$("#autoplay").onchange=e=>{const p=prefs();p.autoplay=e.target.checked;savePrefs(p)};$("#continueToggle").onchange=e=>{const p=prefs();p.continue=e.target.checked;savePrefs(p);renderContinue()};document.querySelectorAll("[data-motion]").forEach(b=>b.onclick=()=>{const p=prefs();p.motion=b.dataset.motion;savePrefs(p)});document.querySelectorAll("[data-density]").forEach(b=>b.onclick=()=>{const p=prefs();p.density=b.dataset.density;savePrefs(p)});
["#search","#modal","#settings","#mobileMenu"].forEach(sel=>$(sel).addEventListener("click",e=>{if(e.target===e.currentTarget){if(sel==="#search")closeSearch();if(sel==="#modal")closeModal();if(sel==="#settings")closeSettings();if(sel==="#mobileMenu")closeMenu()}}));document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;closeSearch();closeModal();closeSettings();closeMenu();if($("#player").classList.contains("open"))closePlayer()});
window.addEventListener("message",e=>{if(typeof e.data!=="string")return;try{const m=JSON.parse(e.data);if(m.type!=="PLAYER_EVENT")return;const d=m.data||{};const id=d.id??d.tmdbId;if(id==null)return;const type=d.mediaType||d.type||"movie";const key=`${type}:${id}${type==="tv"&&d.season!=null?`:${d.season}:${d.episode}`:""}`;const p=getProgress();const progress=Number(d.progress??(d.duration?((Number(d.currentTime||0)/Number(d.duration))*100):0));p[key]={progress:Math.max(0,Math.min(100,progress)),timestamp:Number(d.currentTime||0),duration:Number(d.duration||0),updated:Date.now()};localStorage.setItem("luma-progress",JSON.stringify(p))}catch{}});applyPrefs();home();

// Keep the desktop navigation highlight in sync with the section currently in view.
const navLinks=[...document.querySelectorAll('.nav nav a')];
const navTargets=navLinks.map(a=>({a,id:a.getAttribute('href')?.slice(1)})).filter(x=>x.id&&document.getElementById(x.id));
if('IntersectionObserver' in window){
  const navObserver=new IntersectionObserver(entries=>{
    entries.forEach(entry=>{
      if(entry.isIntersecting){
        navTargets.forEach(x=>x.a.classList.toggle('active',x.id===entry.target.id));
      }
    });
  },{rootMargin:'-35% 0px -55% 0px',threshold:0});
  navTargets.forEach(x=>navObserver.observe(document.getElementById(x.id)));
}
