const $=s=>document.querySelector(s);const IMG="https://image.tmdb.org/t/p/";let cache={},current=null;
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[m]));
const poster=x=>x?.poster_path?IMG+"w500"+x.poster_path:"https://placehold.co/500x750/151617/aaa?text=No+Poster";
const backdrop=x=>x?.backdrop_path?IMG+"original"+x.backdrop_path:poster(x);const title=x=>x?.title||x?.name||"Untitled";const year=x=>(x?.release_date||x?.first_air_date||"").slice(0,4);
const lockBody=on=>document.body.classList.toggle("lock",on);
function card(x){const id=x.id,type=x.media_type||(x.first_air_date?"tv":"movie"),p=getProgress()[`${type}:${id}`];return `<article class="card" data-id="${id}" data-type="${type}"><img loading="lazy" src="${poster(x)}" alt="${esc(title(x))}"><div class="ci"><div class="ct">${esc(title(x))}</div><div class="cm">${year(x)} · ★ ${(x.vote_average||0).toFixed(1)}</div></div>${p?`<div class="bar"><i style="width:${Math.min(100,p.progress||0)}%"></i></div>`:""}</article>`}
function bindCards(){document.querySelectorAll(".card").forEach(c=>c.onclick=()=>details(c.dataset.type,c.dataset.id))}
function getProgress(){try{return JSON.parse(localStorage.getItem("luma-progress")||"{}")}catch{return{}}}
function renderGrid(id,data){$(id).innerHTML=(data||[]).filter(x=>x.poster_path).map(card).join("")||`<p class="muted">Nothing here yet.</p>`;bindCards()}
async function api(path){const r=await fetch(path);const d=await r.json();if(d.error)throw Error(d.error);return d}
async function home(){try{const d=await api("/api/home");const tr=(d.trending?.results||[]).filter(x=>x.media_type!=="person"&&x.backdrop_path);const hero=tr[0];if(hero){current=hero;$("#heroImg").style.backgroundImage=`url('${backdrop(hero)}')`;$("#heroTitle").textContent=title(hero);$("#heroOverview").textContent=hero.overview||"";$("#heroMeta").innerHTML=`<span>${year(hero)}</span><span>•</span><span>${hero.media_type==="tv"?"Series":"Movie"}</span><span>•</span><span>★ ${(hero.vote_average||0).toFixed(1)}</span>`;$("#heroWatch").onclick=()=>play(hero.media_type==="tv"?"tv":"movie",hero.id,hero.media_type==="tv"?1:undefined,hero.media_type==="tv"?1:undefined);$("#heroInfo").onclick=()=>details(hero.media_type,hero.id)}renderGrid("#movieGrid",(d.movies?.results||[]).map(x=>({...x,media_type:"movie"})));renderGrid("#seriesGrid",(d.series?.results||[]).map(x=>({...x,media_type:"tv"})));renderGrid("#topGrid",(d.top?.results||[]).map(x=>({...x,media_type:"movie"})));renderContinue()}catch(e){showSetup(e.message)}}
function showSetup(msg){document.querySelector("main").innerHTML=`<section class="section" style="padding-top:160px"><small>SETUP REQUIRED</small><h2 style="margin-top:10px">Connect TMDB to populate LUMA.</h2><p class="muted">${esc(msg)}</p></section>`}
async function details(type,id){try{const d=await api(`/api/${type}/${id}`);cache[`${type}:${id}`]=d;const genres=(d.genres||[]).map(g=>`<span>${esc(g.name)}</span>`).join("");$("#modalBody").innerHTML=`<div class="cover" style="background-image:linear-gradient(0deg,#151617 0%,transparent 70%),url('${backdrop(d)}')"></div><div class="body"><small>${type==="tv"?"SERIES":"MOVIE"}</small><h2>${esc(title(d))}</h2><div class="chips"><span>${year(d)}</span><span>★ ${(d.vote_average||0).toFixed(1)}</span>${genres}</div><p>${esc(d.overview||"No overview available.")}</p><button class="primary" id="detailWatch">▶ Watch now</button>${type==="tv"?`<div style="margin-top:25px"><label class="muted">Season <select id="seasonSelect">${(d.seasons||[]).filter(s=>s.season_number>0).map(s=>`<option value="${s.season_number}">${esc(s.name)}</option>`).join("")}</select></label><div id="episodes" class="grid" style="grid-template-columns:repeat(3,1fr);margin-top:14px"></div></div>`:""}</div>`;$("#modal").classList.add("open");lockBody(true);$("#detailWatch").onclick=()=>play(type,id,type==="tv"?1:undefined,type==="tv"?1:undefined);if(type==="tv"){const sel=$("#seasonSelect");await season(id,sel.value);sel.onchange=()=>season(id,sel.value)}}catch(e){console.error(e)}}
async function season(id,n){try{const d=await api(`/api/tv/${id}/season/${n}`);$("#episodes").innerHTML=(d.episodes||[]).map(ep=>`<article class="card" data-ep="${ep.episode_number}"><img loading="lazy" src="${poster(ep.still_path?{poster_path:ep.still_path}:null)}" alt="${esc(ep.name)}"><div class="ci"><div class="ct">E${ep.episode_number} · ${esc(ep.name)}</div><div class="cm">${Math.round(ep.runtime||0)} min</div></div></article>`).join("")||`<p class="muted">No episodes found.</p>`;document.querySelectorAll("#episodes .card").forEach(c=>c.onclick=()=>play("tv",id,Number(n),Number(c.dataset.ep)))}catch(e){console.error(e)}}
function play(type,id,season,episode){const accent=($("#accent").value||"d6b77c").replace("#","");const auto=$("#autoplay").value;const p=getProgress()[`${type}:${id}${type==="tv"?`:${season}:${episode}`:""}`];let url=`https://www.vidking.net/embed/${type}/${id}`+(type==="tv"?`/${season||1}/${episode||1}`:"");url+=`?color=${encodeURIComponent(accent)}&autoPlay=${auto}`+(type==="tv"?"&nextEpisode=true&episodeSelector=true":"")+(p?.timestamp?`&progress=${Math.floor(p.timestamp)}`:"");$("#iframe").src=url;$("#player").classList.add("open");lockBody(true);closeModal(true)}
function closeModal(fromPlayer=false){$("#modal").classList.remove("open");if(!fromPlayer)lockBody(false)}
function closePlayer(){$("#iframe").src="about:blank";$("#player").classList.remove("open");lockBody(false)}
function renderContinue(){const p=getProgress(),items=[];for(const [key,v] of Object.entries(p)){if(v.progress>1&&v.progress<99){const [type,id]=key.split(":");const d=cache[`${type}:${id}`];if(d)items.push({...d,media_type:type})}}renderGrid("#continueGrid",items);$("#continueSection").style.display=items.length?"block":"none"}
async function search(q){if(!q){$("#searchResults").innerHTML="";return}try{const d=await api("/api/search?q="+encodeURIComponent(q));$("#searchResults").innerHTML=(d.results||[]).filter(x=>x.media_type!=="person"&&x.poster_path).slice(0,10).map(x=>`<div class="result" data-id="${x.id}" data-type="${x.media_type}"><img src="${poster(x)}" alt="${esc(title(x))}"><div><b>${esc(title(x))}</b><small>${year(x)} · ${x.media_type} · ★ ${(x.vote_average||0).toFixed(1)}</small></div></div>`).join("")||`<p class="muted">No results found.</p>`;document.querySelectorAll(".result").forEach(x=>x.onclick=()=>{closeSearch();details(x.dataset.type,x.dataset.id)})}catch(e){$("#searchResults").innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function discover(){const type=$("#discover").dataset.type||"movie";try{const d=await api(`/api/discover/${type}?sort_by=${encodeURIComponent($("#sort").value)}&with_genres=${$("#genre").value}`);renderGrid("#discoverGrid",(d.results||[]).map(x=>({...x,media_type:type})))}catch(e){console.error(e)}}
function openSearch(){$("#search").classList.add("open");lockBody(true);$("#searchInput").focus()}function closeSearch(){$("#search").classList.remove("open");if(!$("#modal").classList.contains("open")&&!$("#player").classList.contains("open"))lockBody(false)}
function openSettings(){$("#settings").classList.add("open");lockBody(true)}function closeSettings(){$("#settings").classList.remove("open");if(!$("#modal").classList.contains("open")&&!$("#player").classList.contains("open"))lockBody(false)}
$("#searchBtn").onclick=openSearch;$("#closeSearch").onclick=closeSearch;$("#searchInput").oninput=e=>search(e.target.value);$("#closeModal").onclick=()=>closeModal();$("#closePlayer").onclick=closePlayer;$("#settingsBtn").onclick=openSettings;$("#closeSettings").onclick=closeSettings;$("#clearHistory").onclick=()=>{localStorage.removeItem("luma-progress");renderContinue()};document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{$("#discover").classList.remove("hidden");$("#discover").dataset.type=b.dataset.page;location.hash="discover";discover()});$("#sort").onchange=discover;$("#genre").onchange=discover;
window.addEventListener("message",e=>{if(typeof e.data!=="string")return;try{const m=JSON.parse(e.data);if(m.type!=="PLAYER_EVENT")return;const d=m.data;if(!d?.id)return;const type=d.mediaType||"movie";const key=`${type}:${d.id}${type==="tv"&&d.season!=null?`:${d.season}:${d.episode}`:""}`;const p=getProgress();p[key]={progress:Number(d.progress||0),timestamp:Number(d.currentTime||0),duration:Number(d.duration||0),updated:Date.now()};localStorage.setItem("luma-progress",JSON.stringify(p))}catch{}});document.addEventListener("keydown",e=>{if(e.key==="Escape"){if($("#player").classList.contains("open"))closePlayer();else if($("#modal").classList.contains("open"))closeModal();else if($("#search").classList.contains("open"))closeSearch();else if($("#settings").classList.contains("open"))closeSettings()}});home();